# Generated by Django 3.1.1 on 2020-09-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20200905_1746'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('job', 'candidate')},
        ),
    ]
